package("zip")
    set_homepage("https://sourceforge.net/projects/infozip")
    set_description("zip commandline tools")
    set_license("BSD")
    add_urls("https://jaist.dl.sourceforge.net/project/infozip/Zip%203.x%20%28latest%29/3.0/zip30.tar.gz?viasf=1")
    add_versions("v3.0", "f0e8bb1f9b7eb0b01285495a2699df3a4b766784c1765a8f1aeedf63c0806369")

    on_install("linux", function(package)
        os.run("make -f unix/Makefile generic")
        os.cp("zip",package:installdir())
        os.cp("zipnote",package:installdir())
        os.cp("zipsplit",package:installdir())
        os.cp("zipcloak",package:installdir())
        package:addenv("PATH", ".")
    end)

    on_test(function(package)
        os.vrun("zip --help")
    end)
